export default {
    UI: {
      SET_WIP: "SET_WIP",
      UNSET_WIP: "UNSET_WIP"
    },
    CTX: {
      SET_USER: "SET_USER",
      UNSET_USER: "UNSET_USER"
    },
    PRODUCTS: {
      SET_LIST: "PRODUCTS_SET_LIST",
  
      START_ADD: "PRODUCTS_START_ADD",
      CANCEL_ADD: "PRODUCTS_CANCEL_ADD",
      COMPLETE_ADD: "PRODUCTS_COMPLETE_ADD",
  
      START_EDIT: "PRODUCTS_START_EDIT",
      CANCEL_EDIT: "PRODUCTS_CANCEL_EDIT",
      COMPLETE_EDIT: "PRODUCTS_COMPLETE_EDIT",
  
      START_DELETE: "PRODUCTS_START_DELETE",
      CANCEL_DELETE: "PRODUCTS_CANCEL_DELETE",
      COMPLETE_DELETE: "PRODUCTS_COMPLETE_DELETE",
  
      ON_CHANGE: "PRODUCTS_ON_CHANGE"
    }
  };
  